
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TextBook.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ImageTheme
{

    public int IdImage { get; set; }

    public int IdTheme { get; set; }

    public byte[] Image { get; set; }

    public string Name { get; set; }



    public virtual Theme Theme { get; set; }

}

}
