//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAnswer
    {
        public int IdAnswer { get; set; }
        public int IdQuestion { get; set; }
        public string Answer { get; set; }
        public bool Correct { get; set; }
    
        public virtual TestQuestion TestQuestion { get; set; }
    }
}
