
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TextBook.Data
{

using System;
    using System.Collections.Generic;
    
public partial class TestQuestion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TestQuestion()
    {

        this.TestAnswer = new HashSet<TestAnswer>();

    }


    public int IdQuestion { get; set; }

    public int IdTest { get; set; }

    public string TitleQuestion { get; set; }

    public byte[] ImageQuestion { get; set; }



    public virtual Test Test { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TestAnswer> TestAnswer { get; set; }

}

}
