
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TextBook.Data
{

using System;
    using System.Collections.Generic;
    
public partial class TestResult
{

    public int IdResult { get; set; }

    public int IdTest { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public System.TimeSpan Time { get; set; }

    public int CorrectAnswers { get; set; }


    public string NameSurname
        {
            get { return $"{Name} {Surname}"; }
        }

    public System.DateTime DateOfPassage { get; set; }



    public virtual Test Test { get; set; }

}

}
