//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicTest
    {
        public int id { get; set; }
        public int Test { get; set; }
        public int Theme { get; set; }
    
        public virtual Test Test1 { get; set; }
        public virtual Theme Theme1 { get; set; }
    }
}
